### ISSUE TITLE
[UI Issue] : GitHub Stats are overflowing on Mobile View

### ISSUE THREAD

**Issue by TartejBrothers** [mrsnailo/mrsnailo.github.io#100]
# Issue
- In the about page, the mobile view has some overflow issues, the GitHub stats, are overflowing on the x-axis.
![image](https://github.com/mrsnailo/mrsnailo.github.io/assets/112921727/42bc63c4-a0c7-491b-9310-a4d183bb6575)

**Comment by mrsnailo** [comment]
Maybe because of image width is unset,  btw I have switched theme and about  page layout.
